apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /usr/local/bin/kompose -f ./docker-compose.yml convert
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: web
  name: web
spec:
  ports:
  - name: "5015"
    port: 5015
    targetPort: 5000
  selector:
    io.kompose.service: web
status:
  loadBalancer: {}
